const SUPABASE_URL='https://wmqjlbrgdjgfjwopekup.supabase.co';
const SUPABASE_KEY='sb_publishable_N3BSrFZfEidi-nN8hYbWFg_WbjMMsDn';
const {createClient}=supabase;
const db=createClient(SUPABASE_URL,SUPABASE_KEY);
let me=null,currentPage='dashboard',sessionToken=localStorage.getItem('yz_admin_session');
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const roleAllowed=role=>!role||me?.role==='full_admin'||role===me?.role;
function applyAccess(){document.querySelectorAll('[data-role]').forEach(el=>el.classList.toggle('hidden',!roleAllowed(el.dataset.role)))}
function showPage(id){const el=$(id);if(!el||!roleAllowed(el.dataset.role))return;document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden');currentPage=id;const t={dashboard:['الرئيسية','نظرة سريعة على تشغيل المركز'],bookings:['الحجوزات','متابعة طلبات العملاء'],offers:['الأسعار والباقات','تعديلاتك تنعكس على الموقع العام'],ads:['الإعلانات والفعاليات','إدارة المحتوى الظاهر للعملاء']}[id];$('pageTitle').textContent=t[0];$('pageSubtitle').textContent=t[1];if(id==='dashboard')loadDashboard();if(id==='bookings')loadBookings();if(id==='offers')loadOffers();if(id==='ads')loadAds()}
async function rpc(name,args={}){const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
async function loadMe(){if(!sessionToken){showLogin();return}try{const r=await rpc('admin_check',{p_token:sessionToken});if(!r?.length){throw new Error('unauthorized')}me=r[0];$('displayName').textContent=me.display_name;$('roleLabel').textContent=me.role==='full_admin'?'أدمن كامل':'الأسعار والإعلانات';$('avatar').textContent=(me.display_name||'؟').slice(0,1);$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');applyAccess();showPage('dashboard')}catch(e){sessionToken=null;localStorage.removeItem('yz_admin_session');showLogin()}}
function showLogin(){$('loginScreen').classList.remove('hidden');$('app').classList.add('hidden')}
async function login(){$('loginError').textContent='';const u=$('username').value.trim(),p=$('password').value;if(!u||!p)return;try{const r=await rpc('admin_login',{p_username:u,p_password:p});if(!r?.length)throw new Error('bad_login');sessionToken=r[0].session_token;localStorage.setItem('yz_admin_session',sessionToken);await loadMe()}catch(e){$('loginError').textContent='اسم المستخدم أو كلمة المرور غير صحيحة'}}
async function loadDashboard(){if(me.role!=='full_admin')return;try{const d=await rpc('admin_dashboard',{p_token:sessionToken});$('dbStatus').textContent='متصل ويعمل';$('totalBookings').textContent=d.total_bookings||0;$('newBookings').textContent=d.new_bookings||0;$('confirmedBookings').textContent=d.confirmed_bookings||0;$('birthdayBookings').textContent=d.birthday_bookings||0;$('recentBookings').innerHTML=(d.recent||[]).map(x=>`<div class="row"><b>${esc(x.customer_name||'بدون اسم')}</b><br><span>${esc(x.booking_date||'')} · ${x.guests||0} أشخاص · ${esc(x.service_type||'')}</span></div>`).join('')||'لا توجد حجوزات'}catch(e){$('dbStatus').textContent='تعذر الاتصال';$('recentBookings').textContent='تعذر تحميل الحجوزات'}}
async function loadBookings(){try{const data=await rpc('admin_bookings',{p_token:sessionToken});$('bookingCount').textContent=data.length;$('bookingsTable').innerHTML=data.map(x=>`<tr><td><strong>${esc(x.customer_name)}</strong></td><td>${esc(x.customer_phone)}</td><td>${esc(x.booking_date||'')}</td><td>${x.guests||0}</td><td>${esc(x.service_type||'')}</td><td><select onchange="setStatus(${x.id},this.value)"><option value="new" ${x.status==='new'?'selected':''}>جديد</option><option value="confirmed" ${x.status==='confirmed'?'selected':''}>مؤكد</option><option value="cancelled" ${x.status==='cancelled'?'selected':''}>ملغي</option></select></td><td>${esc(x.notes||'')}</td></tr>`).join('')}catch(e){$('bookingsTable').innerHTML='<tr><td colspan="7">تعذر تحميل الحجوزات</td></tr>'}}
window.setStatus=async(id,status)=>{try{await rpc('admin_update_booking_status',{p_token:sessionToken,p_id:id,p_status:status});loadBookings();loadDashboard()}catch(e){alert('تعذر تحديث الحالة')}};
async function loadOffers(){try{const data=await rpc('admin_offers',{p_token:sessionToken});$('offersGrid').innerHTML=data.map(x=>`<article class="entity-card"><strong>${esc(x.name_ar||x.name_en||x.title)}</strong><div class="price">${Number(x.price||0).toLocaleString('ar-SA')} ريال</div><p>${esc(x.description_ar||x.description_en||'')}</p><small>${esc(x.category||'')} · ${x.active?'ظاهر':'مخفي'}</small><div class="actions"><button onclick="editOffer(${x.id})">تعديل</button><button class="danger" onclick="deleteOffer(${x.id})">حذف</button></div></article>`).join('')||'لا توجد باقات'}catch(e){$('offersGrid').textContent='تعذر تحميل الأسعار'}}
window.editOffer=async id=>{try{const data=(await rpc('admin_offers',{p_token:sessionToken})).find(x=>x.id===id);if(data)openOffer(data)}catch(e){alert('تعذر فتح الباقة')}};
window.deleteOffer=async id=>{if(!confirm('حذف الباقة؟'))return;try{await rpc('admin_delete_offer',{p_token:sessionToken,p_id:id});loadOffers()}catch(e){alert('تعذر الحذف')}};
function openOffer(x={}){modalEntity='offer';$('modalTitle').textContent=x.id?'تعديل الباقة':'إضافة باقة';$('entityId').value=x.id||'';$('offerAr').value=x.name_ar||'';$('offerEn').value=x.name_en||'';$('offerDescAr').value=x.description_ar||'';$('offerDescEn').value=x.description_en||'';$('offerPrice').value=x.price??'';$('offerCategory').value=x.category||'general';$('offerActive').checked=x.active!==false;$('offerFields').classList.remove('hidden');$('adFields').classList.add('hidden');$('modal').classList.remove('hidden')}
async function saveOffer(){try{await rpc('admin_upsert_offer',{p_token:sessionToken,p_id:$('entityId').value?Number($('entityId').value):null,p_data:{name_ar:$('offerAr').value.trim(),name_en:$('offerEn').value.trim(),description_ar:$('offerDescAr').value.trim(),description_en:$('offerDescEn').value.trim(),price:Number($('offerPrice').value||0),category:$('offerCategory').value.trim(),active:$('offerActive').checked}});closeModal();loadOffers()}catch(e){$('formError').textContent='تعذر الحفظ: '+e.message}}
async function loadAds(){try{const data=await rpc('admin_ads',{p_token:sessionToken});$('adsGrid').innerHTML=data.map(x=>`<article class="entity-card">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:''}<strong>${esc(x.title||'بدون عنوان')}</strong><p>${esc(x.text||'')}</p><small>${x.active?'ظاهر للعملاء':'مخفي'}</small><div class="actions"><button onclick="editAd('${x.id}')">تعديل</button><button class="danger" onclick="deleteAd('${x.id}')">حذف</button></div></article>`).join('')||'لا توجد إعلانات'}catch(e){$('adsGrid').textContent='تعذر تحميل الإعلانات'}}
window.editAd=async id=>{try{const data=(await rpc('admin_ads',{p_token:sessionToken})).find(x=>x.id===id);if(data)openAd(data)}catch(e){alert('تعذر فتح الإعلان')}};
window.deleteAd=async id=>{if(!confirm('حذف الإعلان؟'))return;try{await rpc('admin_delete_ad',{p_token:sessionToken,p_id:id});loadAds()}catch(e){alert('تعذر الحذف')}};
function openAd(x={}){modalEntity='ad';$('modalTitle').textContent=x.id?'تعديل الإعلان':'إضافة إعلان / فعالية';$('entityId').value=x.id||'';$('adTitle').value=x.title||'';$('adBody').value=x.text||'';$('adImage').value=x.image_url||'';$('adTarget').value=x.target_url||'';$('adActive').checked=x.active!==false;$('offerFields').classList.add('hidden');$('adFields').classList.remove('hidden');$('modal').classList.remove('hidden')}
async function saveAd(){try{await rpc('admin_upsert_ad',{p_token:sessionToken,p_id:$('entityId').value||null,p_data:{title:$('adTitle').value.trim(),text:$('adBody').value.trim(),image_url:$('adImage').value.trim()||null,target_url:$('adTarget').value.trim()||null,active:$('adActive').checked}});closeModal();loadAds()}catch(e){$('formError').textContent='تعذر الحفظ: '+e.message}}
let modalEntity='offer';function closeModal(){$('modal').classList.add('hidden');$('formError').textContent=''}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();login()});$('logout').addEventListener('click',async()=>{try{if(sessionToken)await rpc('admin_logout',{p_token:sessionToken})}finally{sessionToken=null;localStorage.removeItem('yz_admin_session');location.reload()}});document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));$('refresh').addEventListener('click',()=>showPage(currentPage));$('newOffer').addEventListener('click',()=>openOffer());$('newAd').addEventListener('click',()=>openAd());$('closeModal').addEventListener('click',closeModal);$('editorForm').addEventListener('submit',e=>{e.preventDefault();modalEntity==='offer'?saveOffer():saveAd()});loadMe();
